language: shell

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change

git:
  submodules: false

jobs:
  include:
  - os: osx
    osx_image: xcode12.2
    env: OS_NAME="osx" OS_VERSION="10.15.7" OS_BUILD="brew" OS_DEPLOY="false"
  - os: osx
    osx_image: xcode11.3
    env: OS_NAME="osx" OS_VERSION="10.14.6" OS_BUILD="brew" OS_DEPLOY="false"
  - os: osx
    osx_image: xcode10.1
    env: OS_NAME="osx" OS_VERSION="10.13" OS_BUILD="brew" OS_DEPLOY="false"
  - os: osx
    osx_image: xcode9
    env: OS_NAME="osx" OS_VERSION="10.12" OS_BUILD="brew" OS_DEPLOY="false"

before_install:
  - chmod a+x ./.travis/before_install.sh
  - "./.travis/before_install.sh"

script:
  - chmod a+x ./build.sh
  - "./build.sh"

deploy:
  provider: releases
  skip-cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  file:
  - dist/*
  on:
    branch: master
    tags: false
    condition: OS_DEPLOY="true"
